### ISSUE TITLE
0.7.0 release checklist

### ISSUE THREAD

**Issue by livid** [Planetable/Planet#27]
## Blockers

- [x] Threading issues when checking for updates or rebuilding the whole site
- [x] Add video support to all built-in templates

## To Test

- [x] Test the new saver for data migration
- [x] Test the complete flow of creating and editing articles with video
- [x] Test the new writer with various screen dimensions
- [x] Test content update
- [x] Test import/export between 0.6 and 0.7

## Procedure

- [x] Build and archive for internal testing on 3+ environments
- [x] Release
